import type { Metadata } from 'next';
import './index.css';
import { Header } from '@/widgets';

export const metadata: Metadata = {
  title: 'VOTalks : Vote & Talks',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="">
        <Header />
        <section id="contents" className="m-auto min-h-full max-w-5xl pb-12 pt-14 sm:pt-16">
          {children}
        </section>
      </body>
    </html>
  );
}
